---
- name: 
  hosts: all
  become: yes
  tasks: 
  - name: Update repositories
    apt:
      update_cache: yes

  - name: Show python version
    debug:
      msg: The python version is {{ ansible_facts.python_version }}

  - name: Ensure vim is installed
    apt:
      state: present

  - name: Ensure vimrc is deployed
    copy:
      src: /vagrant/provision/files/vimrc
      dest: /home/vagrant/.vimrc
      owner: vagrant
      mode: '664'

  - name: Ensure .vim directory and files are owned by vagrant user and group
    file:
      path: /home/vagrant/.vim
      state: directory
      recurse: yes
      owner: vagrant
      group: vagrant

  - name: Ensure Vundle plugin manager is installed
    git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: /home/vagrant/.vim/bundle/Vundle.vim
    become: yes
    become_user: vagrant # Needed to avoid Git security compliance: https://stackoverflow.com/questions/72299489/unsafe-repository-owned-by-someone-else-ok-but-who

  # Idempotent but not declarative. TODO
  - name: Install vim plugins via Vundle
    #shell: echo -ne '\n' | vim -E -s -c "source /home/vagrant/.vimrc" -c PluginInstall -c qa
    shell: vim +PluginInstall +qall! 
    become: yes
    become_user: vagrant

  # Project directories and provisioning
  - name: Create projects folder
    file:
      path: /home/vagrant/devel/ # TODO: Get values from variables
      state: directory
      recurse: yes
      owner: vagrant  # TODO: Get user value from variable
      group: vagrant   # TODO: Get user value from variable

  # TODO: Git init and git clone tasks
  # TODO: Config ssh keys for github repos

  - name: Ensure bash git prompt is deployed
    git:
      repo: https://github.com/magicmonty/bash-git-prompt.git
      dest: ~/.bash-git-prompt # TODO: abstract this intro env variable based on another variable pointing to the user
    become_user: vagrant # TODO: view above 

  # TODO: modify bashrc to add call to bash-git prompt
  - name: Ensure call to bash-git-prompt from .bashrc
    blockinfile:
      insertafter: EOF
      backup: yes
      block: |
        GIT_PROMPT_ONLY_IN_REPO=1
        GIT_PROMPT_THEME=Single_line
        source ~/.bash-git-prompt/gitprompt.sh
      path: ~/.bashrc
    become_user: vagrant # TODO: abstract this intro env variable based on another variable pointing to the use
